language: python
python:
  - "3.8"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install -e gin_tune
  - pip install -e .
# command to run tests
script:
  - ./tests.sh
services: mongodb
